# Generated by Django 3.2.23 on 2023-12-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=200)),
                ('question', models.TextField(blank=True)),
                ('question_difficulty', models.CharField(max_length=200)),
                ('option_A', models.CharField(max_length=200)),
                ('option_B', models.CharField(max_length=200)),
                ('option_C', models.CharField(max_length=200)),
                ('option_D', models.CharField(max_length=200)),
                ('answer_option', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
