# Generated by Django 3.2.23 on 2023-12-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20231216_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz1',
            name='question_difficulty',
        ),
    ]
