# Generated by Django 4.2.8 on 2023-12-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IT_Person", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="AuthGroup",),
        migrations.DeleteModel(name="AuthGroupPermissions",),
        migrations.DeleteModel(name="AuthPermission",),
        migrations.DeleteModel(name="AuthUser",),
        migrations.DeleteModel(name="AuthUserGroups",),
        migrations.DeleteModel(name="AuthUserUserPermissions",),
        migrations.DeleteModel(name="DjangoAdminLog",),
        migrations.DeleteModel(name="DjangoContentType",),
        migrations.DeleteModel(name="DjangoMigrations",),
        migrations.DeleteModel(name="DjangoSession",),
        migrations.DeleteModel(name="Employees",),
    ]
