# Generated by Django 4.2.8 on 2023-12-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("IT_Person", "0002_delete_authgroup_delete_authgrouppermissions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pemails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pemail", models.CharField(max_length=100)),
                ("apppwd", models.CharField(max_length=100)),
            ],
        ),
    ]
