# Generated by Django 4.2.8 on 2023-12-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IT_Person", "0004_alter_pemails_pemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pemails_content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pemail",
                    models.EmailField(max_length=120, verbose_name="phishing email"),
                ),
                ("content", models.CharField(max_length=100)),
            ],
        ),
    ]
