# Generated by Django 4.2.8 on 2023-12-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IT_Person", "0005_pemails_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="pemails_content",
            name="emp_email",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="emp_email"
            ),
        ),
        migrations.AddField(
            model_name="pemails_content",
            name="emp_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="emp_name"
            ),
        ),
        migrations.AddField(
            model_name="pemails_content",
            name="recent_project",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="recent_project"
            ),
        ),
        migrations.AlterField(
            model_name="pemails_content",
            name="content",
            field=models.TextField(max_length=1000),
        ),
    ]
